### PR TITLE
Remove HISTORY.md

### PR DESCRIPTION
**Pull request by mkarg**
> I am pretty sure you want record this great day in the HISTORY.md file! ;-)

Proposal: Removing the file.

### CODE REVIEW

**Review by slawekjaranowski — DISMISSED** [review]
Ok, we can add this information.

But in the feature I don't want to maintain this file.
It was only create to show initial history of plugin, now we have new history.

Releases history is created automatically at GitHub releases page.

**Comment by mkarg** [comment]
Ok, so why not simply drop this file then?

**Comment by slawekjaranowski** [comment]
Then we lost information, why project was created and where idea was born.
I think is is ok, to have separate file for this information.

**Comment by mkarg** [comment]
I do not see any benefit from keeping this information. Who would care about it?

**Comment by slawekjaranowski** [comment]
I only wanted to be polite. 
If you think that it is not necessary - we can remove this file.

**Comment by mkarg** [comment]
Being polite is always nice, but I do not see a benefit from the file itself. We could simply have that information be stored in a wiki or web site. Hence I changed this PR to get rid of the file.

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
