### PR TITLE
[8] Signature file name should contain version

### LINKED ISSUE #8: Signature file name should contain version
currently signature file don't have version in name, eg we have:

```
target/artifactName-Version.jar
target/artifactName.jar.asc
```

should be:

```
target/artifactName-Version.jar
target/artifactName-Version.jar.asc
```

It doesn't has impact on result because proper artifact is attached

### PR DESCRIPTION
**Pull request by mkarg**
Puts version number right before extension in signature file name.

Closes #8

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
It will be good to have some assertions for it. 
We can add `postbuild.groovy` to ITs tests and verify if correct filename was created.

**Comment by mkarg** [comment]
I thnk that this is not related to this specific PR and something missing / useful independently. Do you file an issue for it?

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
ok, verification can be in next change

**Comment by mkarg** [comment]
Filed issue https://github.com/s4u/sign-maven-plugin/issues/19 for this.

**Pull request merged**
